### PR TITLE
import_from_curl: add support for parsing (basic) curl commandlines

### PR DESCRIPTION
**Pull request by cfcs**
`import_from_curl()`: add support for parsing (basic) curl command-lines and creating corresponding Requests / RequestSets

This PR adds the function `import_from_curl` to `burst/external.py`.
The function accepts the curl command-line as an argument of types `str` (using `shlex.split` to parse quotes) or `list` (argv-style). If no argument is given, the command-line is obtained from `raw_input()` (to accommodate easy copy-pasting).

Curl-style range-sequences are expanded using `inject()`, but the `{one,two,three}` syntax is not currently implemented. Use of this feature makes the function return a `RequestSet` rather than a `Request`.

Example run:
```
>>> a=import_from_curl()
curl cmdline: curl --header a:b https://localhost/?id=[0-2:1]&page=[0-2]
>>> p a[0]
GET /?id=0&page=0 HTTP/1.1
Host: localhost
User-Agent: Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 0.9; en-US)
Accept-Encoding: gzip, deflate
a: b
Content-Length: 0


>>> p a[4]
GET /?id=1&page=1 HTTP/1.1
Host: localhost
User-Agent: Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 0.9; en-US)
Accept-Encoding: gzip, deflate
a: b
Content-Length: 0
```

### CODE REVIEW

**Comment by tweksteen** [comment]
Thanks for the patch!

I have few comments on the code. First, on the general approach. From my understanding, you are first reading all the options of the command line, populating a temporary dictionary and then building a request from its textual representation. With this approach, you may come across parsing issues that may have already been addressed or should be implemented somewhere else in the code. (I'm thinking URL parsing, which should be part of create()). What about first trying to find the URL in the options, pass this URL to create() and then modify the Request object itself depending on the remaining options (add headers, modify content, etc)? 

The arguments expansion can also happen later on and even be part of Request itself. It could be a great way to generate RequestSet in general, not necessarily when importing from a command line.
(i.e., something like `rs = r.expand_curl_arguments()`). (Of course, this would still be called as the last stage of the import).

I really like the fact that you track which options are supported and which are not. I don't mind too much the fact that you fallback on raw_input (avoid extra typing of quotes?).

**Comment by cfcs** [comment]
I'm working on a new commit for tihs to address your concerns:

- I agree with the `create()` approach, I'll use that. Still getting used to this code base :-)

- I agree that argument expansion in general would be nice, and it should happen as late as possible so that expandable arguments can be added "pythonically". I'm leaning towards either making it an auxiliary stand-alone function that takes either a `Request` or a `RequestSet`, or a making it a property of `RequestSet`. That way it can just extend its own `Request` collection.

Yes, exactly @ raw_input. Perhaps there should be a check whether or not it's an interactive session. Do you have such conditions elsewhere?

**Comment by cfcs** [comment]
Update:
- I implemented is a method of `Request` (`expand_curl_ranges()`) that returns a `RequestSet`
- I made a wrapper function in `RequestSet` that calls `Request.expand_curl_ranges()` on all members modifies `self` in place
- Refactoring this made it fairly easy to add support for character ranges and `{a,b,c}`-style braces, a nice addition IMHO.

Happy to hear your comments :-)

**Comment by tweksteen** [comment]
Thanks!

What I might do at this stage is to create a new branch so we can work on this feature (and all the other missing that you've come across :)) I'll merge it to master when it will be stable enough.

**Pull request merged**
